"""empty message

Revision ID: 7c7be4eeb979
Revises: 
Create Date: 2021-04-11 03:52:33.364044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7be4eeb979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'saved_preset', ['preset_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_preset', type_='unique')
    # ### end Alembic commands ###
